apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: db
  namespace: vote
spec:
  podSelector:
    matchLabels:
      app: db
      version: v1
  listeners:
    - portMapping:
        port: 5432
        protocol: tcp
      healthCheck:
        protocol: tcp
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  backends:
    - virtualService:
        virtualServiceRef:
          name: db
  serviceDiscovery:
    dns:
      hostname: db-v1.vote.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: db
  namespace: vote
spec:
  awsName: db.vote.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: db-router
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: db-router
  namespace: vote
spec:
  listeners:
    - portMapping:
        port: 5432
        protocol: tcp
  routes:
    - name: db-route
      tcpRoute:
        action:
          weightedTargets:
            - virtualNodeRef:
                name: db
              weight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
  labels:
    app: db
spec:
  ports:
  - port: 5432
    name: tcp
