apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:9.4
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: true
      volumes:
      - name: db-data
        emptyDir: {}
