apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
spec:
  selector:
    matchLabels:
      app: db
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        version: v1
    spec:
      containers:
      - image: postgres:9.4
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      volumes:
      - name: db-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db-v1
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db
    version: v1
