apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:9.4
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      volumes:
      - name: db-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db-v1
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db
---
# DB
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: db-v1
  namespace: vote
spec:
  podSelector:
    matchLabels:
      app: db
  listeners:
    - portMapping:
        port: 5432
        protocol: tcp
      healthCheck:
        protocol: tcp
        path: '/'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  serviceDiscovery:
    dns:
      hostname: db.vote.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: db
  namespace: vote
spec:
  awsName: db.vote.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: db-router
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: db-router
  namespace: vote
spec:
  listeners:
    - portMapping:
        port: 5432
        protocol: http
  routes:
    - name: vote-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: db-v1
              weight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
  labels:
    app: db
spec:
  ports:
  - port: 5432
    name: tcp