apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: vote
spec:
  selector:
    matchLabels:
      app: result
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: CONTAINER_IMAGE
        name: result
