apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: vote
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: CONTAINER_IMAGE
        name: vote
