apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  selector:
    matchLabels:
      app: worker
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
        version: v1
    spec:
      containers:
      - image: CONTAINER_IMAGE
      # - image: 111706684826.dkr.ecr.us-east-1.amazonaws.com/demo/worker:738886c588d7967fde9d91a04e1d0dcb0deac01a
        name: worker
